# Generated by Django 5.1.3 on 2024-12-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_total_price_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price_per_ticket',
            field=models.PositiveIntegerField(),
        ),
    ]
