# Generated by Django 5.1.3 on 2024-12-19 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price_per_ticket',
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.event'),
        ),
    ]
