# Generated by Django 5.1.3 on 2024-12-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_price_per_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_per_ticket',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
